import type { MapData } from '@circlemap/core'

export const ff46Data: MapData = {
  venue: {
    id: 'ff46',
    name: 'FF46',
    size: { width: 12000, height: 8000 }, // Scaled coordinate system
    outlinePoints: [
      { x: 3000, y: 0 },
      { x: 12000, y: 0 },
      { x: 12000, y: 8000 },
      { x: 0, y: 8000 },
      { x: 0, y: 2200 },
      { x: 3000, y: 2200 },
    ], // Polygon outline for the building, with the top-left corner cut out
    obstacles: [
      // Top row pillars
      { id: 'p1', position: { x: 3400, y: 1100 }, size: { width: 250, height: 250 }, color: '#000000' },
      { id: 'p2', position: { x: 5800, y: 1100 }, size: { width: 250, height: 250 }, color: '#000000' },
      { id: 'p3', position: { x: 8200, y: 1100 }, size: { width: 250, height: 250 }, color: '#000000' },
      { id: 'p4', position: { x: 10600, y: 1100 }, size: { width: 250, height: 250 }, color: '#000000' },

      // Left side pillars
      { id: 'p5', position: { x: 600, y: 3900 }, size: { width: 250, height: 250 }, color: '#000000' },
      { id: 'p6', position: { x: 600, y: 6400 }, size: { width: 250, height: 250 }, color: '#000000' },

      // Internal structural pillars (M ~ A row gap)
      { id: 'p7', position: { x: 2000, y: 4000 }, size: { width: 250, height: 250 }, color: '#000000' },
      { id: 'p8', position: { x: 3400, y: 4000 }, size: { width: 250, height: 250 }, color: '#000000' },
      { id: 'p9', position: { x: 4600, y: 4000 }, size: { width: 250, height: 250 }, color: '#000000' }, // L/K gap
      { id: 'p10', position: { x: 6900, y: 4000 }, size: { width: 250, height: 250 }, color: '#000000' }, // H gap
      { id: 'p11', position: { x: 9200, y: 4000 }, size: { width: 250, height: 250 }, color: '#000000' }, // E gap

      // Bottom pillars
      { id: 'p12', position: { x: 2000, y: 6600 }, size: { width: 250, height: 250 }, color: '#000000' },
      { id: 'p13', position: { x: 3000, y: 6600 }, size: { width: 250, height: 250 }, color: '#000000' },
      { id: 'p14', position: { x: 4500, y: 6600 }, size: { width: 250, height: 250 }, color: '#000000' },
      { id: 'p15', position: { x: 5800, y: 6600 }, size: { width: 250, height: 250 }, color: '#000000' },
      { id: 'p16', position: { x: 6700, y: 6600 }, size: { width: 250, height: 250 }, color: '#000000' },
      { id: 'p17', position: { x: 8200, y: 6600 }, size: { width: 250, height: 250 }, color: '#000000' },
      { id: 'p18', position: { x: 10600, y: 6600 }, size: { width: 250, height: 250 }, color: '#000000' },
    ],
  },
  facilities: [
    { id: 'f_hq', type: 'HQ', position: { x: 1000, y: 2500 }, size: { width: 300, height: 600 }, label: '總部' },
    { id: 'f_stage', type: 'STAGE', position: { x: 1000, y: 3400 }, size: { width: 600, height: 700 }, label: '舞台' },
    {
      id: 'f_entry1',
      type: 'ENTRANCE',
      position: { x: 600, y: 6900 },
      size: { width: 1400, height: 200 },
      label: '快速入場券入口 / 貴賓券入口',
      direction: 'UP',
    },
    {
      id: 'f_entry2',
      type: 'ENTRANCE',
      position: { x: 3400, y: 6900 },
      size: { width: 800, height: 200 },
      label: '電子福袋組入口2',
      direction: 'UP',
    },
    {
      id: 'f_entry3',
      type: 'ENTRANCE',
      position: { x: 4600, y: 6900 },
      size: { width: 800, height: 200 },
      label: '電子福袋組入口',
      direction: 'UP',
    },
    {
      id: 'f_entry4',
      type: 'ENTRANCE',
      position: { x: 6000, y: 6900 },
      size: { width: 1500, height: 200 },
      label: '一般入口',
      direction: 'UP',
    },
    {
      id: 'f_ticket',
      type: 'TICKET',
      position: { x: 8200, y: 6900 },
      size: { width: 1000, height: 400 },
      label: '售票處',
    },
  ],
  boothBlocks: [
    // Bottom Rows (A ~ M) - U Shape
    {
      id: 'b_A',
      type: 'standard_row',
      prefix: 'A',
      position: { x: 10800, y: 4400 },
      size: { width: 240, height: 2640 },
      layoutConfig: {
        columns: 2,
        startNumber: 1,
        endNumber: 44,
        numberingDirection: 'serpentine',
        startCorner: 'bottom_right',
      },
    },
    {
      id: 'b_B',
      type: 'standard_row',
      prefix: 'B',
      position: { x: 10200, y: 4400 },
      size: { width: 240, height: 2640 },
      layoutConfig: {
        columns: 2,
        startNumber: 1,
        endNumber: 44,
        numberingDirection: 'serpentine',
        startCorner: 'bottom_right',
      },
    },
    {
      id: 'b_C',
      type: 'standard_row',
      prefix: 'C',
      position: { x: 9600, y: 4400 },
      size: { width: 240, height: 2640 },
      layoutConfig: {
        columns: 2,
        startNumber: 1,
        endNumber: 44,
        numberingDirection: 'serpentine',
        startCorner: 'bottom_right',
      },
    },
    {
      id: 'b_D',
      type: 'standard_row',
      prefix: 'D',
      position: { x: 9000, y: 4400 },
      size: { width: 240, height: 2640 },
      layoutConfig: {
        columns: 2,
        startNumber: 1,
        endNumber: 44,
        numberingDirection: 'serpentine',
        startCorner: 'bottom_right',
      },
    },
    {
      id: 'b_E',
      type: 'standard_row',
      prefix: 'E',
      position: { x: 8400, y: 4400 },
      size: { width: 240, height: 2640 },
      layoutConfig: {
        columns: 2,
        startNumber: 1,
        endNumber: 44,
        numberingDirection: 'serpentine',
        startCorner: 'bottom_right',
      },
    },
    {
      id: 'b_F',
      type: 'standard_row',
      prefix: 'F',
      position: { x: 7800, y: 4400 },
      size: { width: 240, height: 2640 },
      layoutConfig: {
        columns: 2,
        startNumber: 1,
        endNumber: 44,
        numberingDirection: 'serpentine',
        startCorner: 'bottom_right',
      },
    },
    {
      id: 'b_G',
      type: 'standard_row',
      prefix: 'G',
      position: { x: 7200, y: 4400 },
      size: { width: 240, height: 2640 },
      layoutConfig: {
        columns: 2,
        startNumber: 1,
        endNumber: 44,
        numberingDirection: 'serpentine',
        startCorner: 'bottom_right',
      },
    },
    {
      id: 'b_H',
      type: 'standard_row',
      prefix: 'H',
      position: { x: 6600, y: 4400 },
      size: { width: 240, height: 2640 },
      layoutConfig: {
        columns: 2,
        startNumber: 1,
        endNumber: 44,
        numberingDirection: 'serpentine',
        startCorner: 'bottom_right',
      },
    },
    {
      id: 'b_I',
      type: 'standard_row',
      prefix: 'I',
      position: { x: 6000, y: 4400 },
      size: { width: 240, height: 2640 },
      layoutConfig: {
        columns: 2,
        startNumber: 1,
        endNumber: 44,
        numberingDirection: 'serpentine',
        startCorner: 'bottom_right',
      },
    },
    {
      id: 'b_J',
      type: 'standard_row',
      prefix: 'J',
      position: { x: 5400, y: 4400 },
      size: { width: 240, height: 2640 },
      layoutConfig: {
        columns: 2,
        startNumber: 1,
        endNumber: 44,
        numberingDirection: 'serpentine',
        startCorner: 'bottom_right',
      },
    },
    {
      id: 'b_K',
      type: 'standard_row',
      prefix: 'K',
      position: { x: 4800, y: 4400 },
      size: { width: 240, height: 2640 },
      layoutConfig: {
        columns: 2,
        startNumber: 1,
        endNumber: 44,
        numberingDirection: 'serpentine',
        startCorner: 'bottom_right',
      },
    },
    {
      id: 'b_L',
      type: 'standard_row',
      prefix: 'L',
      position: { x: 4200, y: 4400 },
      size: { width: 240, height: 2640 },
      layoutConfig: {
        columns: 2,
        startNumber: 1,
        endNumber: 44,
        numberingDirection: 'serpentine',
        startCorner: 'bottom_right',
      },
    },
    {
      id: 'b_M',
      type: 'standard_row',
      prefix: 'M',
      position: { x: 3600, y: 4400 },
      size: { width: 240, height: 2640 },
      layoutConfig: {
        columns: 2,
        startNumber: 1,
        endNumber: 44,
        numberingDirection: 'serpentine',
        startCorner: 'bottom_right',
      },
    },

    // Top Rows (N ~ V)
    {
      id: 'b_N',
      type: 'standard_row',
      prefix: 'N',
      position: { x: 9100, y: 1600 },
      size: { width: 240, height: 2640 },
      layoutConfig: {
        columns: 2,
        startNumber: 1,
        endNumber: 44,
        numberingDirection: 'serpentine',
        startCorner: 'bottom_right',
      },
    },
    {
      id: 'b_O',
      type: 'standard_row',
      prefix: 'O',
      position: { x: 8400, y: 1600 },
      size: { width: 240, height: 2640 },
      layoutConfig: {
        columns: 2,
        startNumber: 1,
        endNumber: 44,
        numberingDirection: 'serpentine',
        startCorner: 'bottom_right',
      },
    },
    {
      id: 'b_P',
      type: 'standard_row',
      prefix: 'P',
      position: { x: 7800, y: 1600 },
      size: { width: 240, height: 2640 },
      layoutConfig: {
        columns: 2,
        startNumber: 1,
        endNumber: 44,
        numberingDirection: 'serpentine',
        startCorner: 'bottom_right',
      },
    },
    {
      id: 'b_Q',
      type: 'standard_row',
      prefix: 'Q',
      position: { x: 7200, y: 1600 },
      size: { width: 240, height: 2640 },
      layoutConfig: {
        columns: 2,
        startNumber: 1,
        endNumber: 44,
        numberingDirection: 'serpentine',
        startCorner: 'bottom_right',
      },
    },
    {
      id: 'b_R',
      type: 'standard_row',
      prefix: 'R',
      position: { x: 6600, y: 1600 },
      size: { width: 240, height: 2640 },
      layoutConfig: {
        columns: 2,
        startNumber: 1,
        endNumber: 44,
        numberingDirection: 'serpentine',
        startCorner: 'bottom_right',
      },
    },
    {
      id: 'b_S',
      type: 'standard_row',
      prefix: 'S',
      position: { x: 6000, y: 1600 },
      size: { width: 240, height: 2640 },
      layoutConfig: {
        columns: 2,
        startNumber: 1,
        endNumber: 44,
        numberingDirection: 'serpentine',
        startCorner: 'bottom_right',
      },
    },
    {
      id: 'b_T',
      type: 'standard_row',
      prefix: 'T',
      position: { x: 5400, y: 1600 },
      size: { width: 240, height: 2640 },
      layoutConfig: {
        columns: 2,
        startNumber: 1,
        endNumber: 44,
        numberingDirection: 'serpentine',
        startCorner: 'bottom_right',
      },
    },
    {
      id: 'b_U',
      type: 'standard_row',
      prefix: 'U',
      position: { x: 4800, y: 1600 },
      size: { width: 240, height: 2640 },
      layoutConfig: {
        columns: 2,
        startNumber: 1,
        endNumber: 44,
        numberingDirection: 'serpentine',
        startCorner: 'bottom_right',
      },
    },
    {
      id: 'b_V',
      type: 'standard_row',
      prefix: 'V',
      position: { x: 4200, y: 1600 },
      size: { width: 240, height: 2640 },
      layoutConfig: {
        columns: 2,
        startNumber: 1,
        endNumber: 44,
        numberingDirection: 'serpentine',
        startCorner: 'bottom_right',
      },
    },

    // Top Horizontal Row (W)
    {
      id: 'b_W1',
      type: 'standard_row',
      prefix: 'W',
      position: { x: 8800, y: 1200 },
      size: { width: 720, height: 120 },
      layoutConfig: {
        columns: 1,
        startNumber: 1,
        endNumber: 6,
        numberingDirection: 'same_direction',
        startCorner: 'top_right',
      },
    },
    {
      id: 'b_W2',
      type: 'standard_row',
      prefix: 'W',
      position: { x: 7200, y: 1200 },
      size: { width: 1320, height: 120 },
      layoutConfig: {
        columns: 1,
        startNumber: 7,
        endNumber: 14,
        numberingDirection: 'same_direction',
        startCorner: 'top_right',
      },
    },
    {
      id: 'b_W3',
      type: 'standard_row',
      prefix: 'W',
      position: { x: 5900, y: 1200 },
      size: { width: 1200, height: 120 },
      layoutConfig: {
        columns: 1,
        startNumber: 15,
        endNumber: 24,
        numberingDirection: 'same_direction',
        startCorner: 'top_right',
      },
    },
    {
      id: 'b_W4',
      type: 'standard_row',
      prefix: 'W',
      position: { x: 4600, y: 1200 },
      size: { width: 1200, height: 120 },
      layoutConfig: {
        columns: 1,
        startNumber: 25,
        endNumber: 34,
        numberingDirection: 'same_direction',
        startCorner: 'top_right',
      },
    },
    {
      id: 'b_W5',
      type: 'standard_row',
      prefix: 'W',
      position: { x: 3800, y: 1200 },
      size: { width: 960, height: 120 },
      layoutConfig: {
        columns: 1,
        startNumber: 35,
        endNumber: 42,
        numberingDirection: 'same_direction',
        startCorner: 'top_right',
      },
    },
  ],
  specialZones: [
    {
      id: 'sz_melonbooks',
      label: 'Melon\nBooks',
      points: [
        { x: 1000, y: 4400 },
        { x: 1600, y: 4400 },
        { x: 1600, y: 5200 },
        { x: 1000, y: 5200 },
      ],
      backgroundColor: 'rgba(255, 255, 255, 1)',
      textColor: '#000000',
      textAlign: 'CENTER',
      verticalAlign: 'MIDDLE',
    },
    {
      id: 'sz_toypla',
      label: 'TOYPLA',
      points: [
        { x: 550, y: 4200 },
        { x: 950, y: 4200 },
        { x: 950, y: 6600 },
        { x: 550, y: 6600 },
      ],
      backgroundColor: 'rgba(255, 255, 255, 1)',
      textColor: '#000000',
      textAlign: 'CENTER',
      verticalAlign: 'MIDDLE',
    },
    {
      id: 'sz_alg',
      label: 'ALG-Vtuber',
      points: [
        { x: 9800, y: 1600 },
        { x: 10400, y: 1600 },
        { x: 10400, y: 3600 },
        { x: 9800, y: 3600 },
      ],
      backgroundColor: 'rgba(255, 255, 255, 1)',
      textColor: '#000000',
      textAlign: 'CENTER',
      verticalAlign: 'MIDDLE',
    },
    {
      id: 'sz_mango',
      label: '芒果\n派對',
      points: [
        { x: 9800, y: 3700 },
        { x: 10400, y: 3700 },
        { x: 10400, y: 4300 },
        { x: 9800, y: 4300 },
      ],
      backgroundColor: 'rgba(255, 255, 255, 1)',
      textColor: '#000000',
      textAlign: 'CENTER',
      verticalAlign: 'MIDDLE',
    },
    {
      id: 'sz_dlsite',
      label: 'DLsite',
      points: [
        { x: 10800, y: 1000 },
        { x: 11200, y: 1000 },
        { x: 11200, y: 6600 },
        { x: 10800, y: 6600 },
      ],
      backgroundColor: 'rgba(255, 255, 255, 1)',
      textColor: '#000000',
      textAlign: 'CENTER',
      verticalAlign: 'MIDDLE',
    },
  ],
}
